name: Fabio Salvalai
tagline: Senior Full Stack Software Engineer
location: Lausanne, Switzerland
employer: SwissCaution
github: salfab
linkedin: fabio-salvalai
domain: seesharp.ch

url: "https://seesharp.ch"
baseurl: ""

markdown: kramdown
